// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pkg/proto/inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecreaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockRequest) Reset() {
	*x = DecreaseStockRequest{}
	mi := &file_pkg_proto_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockRequest) ProtoMessage() {}

func (x *DecreaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockRequest.ProtoReflect.Descriptor instead.
func (*DecreaseStockRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *DecreaseStockRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *DecreaseStockRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DecreaseStockRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecreaseStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DecreaseStockRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type DecreaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockResponse) Reset() {
	*x = DecreaseStockResponse{}
	mi := &file_pkg_proto_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockResponse) ProtoMessage() {}

func (x *DecreaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockResponse.ProtoReflect.Descriptor instead.
func (*DecreaseStockResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *DecreaseStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DecreaseStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_inventory_inventory_proto protoreflect.FileDescriptor

const file_pkg_proto_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"#pkg/proto/inventory/inventory.proto\x12\tinventory\"\x99\x01\n" +
	"\x14DecreaseStockRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"K\n" +
	"\x15DecreaseStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2f\n" +
	"\x10InventoryService\x12R\n" +
	"\rDecreaseStock\x12\x1f.inventory.DecreaseStockRequest\x1a .inventory.DecreaseStockResponseB\"Z vv-ecommerce/pkg/proto/inventoryb\x06proto3"

var (
	file_pkg_proto_inventory_inventory_proto_rawDescOnce sync.Once
	file_pkg_proto_inventory_inventory_proto_rawDescData []byte
)

func file_pkg_proto_inventory_inventory_proto_rawDescGZIP() []byte {
	file_pkg_proto_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_pkg_proto_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_inventory_inventory_proto_rawDesc), len(file_pkg_proto_inventory_inventory_proto_rawDesc)))
	})
	return file_pkg_proto_inventory_inventory_proto_rawDescData
}

var file_pkg_proto_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_inventory_inventory_proto_goTypes = []any{
	(*DecreaseStockRequest)(nil),  // 0: inventory.DecreaseStockRequest
	(*DecreaseStockResponse)(nil), // 1: inventory.DecreaseStockResponse
}
var file_pkg_proto_inventory_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryService.DecreaseStock:input_type -> inventory.DecreaseStockRequest
	1, // 1: inventory.InventoryService.DecreaseStock:output_type -> inventory.DecreaseStockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_inventory_inventory_proto_init() }
func file_pkg_proto_inventory_inventory_proto_init() {
	if File_pkg_proto_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_inventory_inventory_proto_rawDesc), len(file_pkg_proto_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_pkg_proto_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_pkg_proto_inventory_inventory_proto_msgTypes,
	}.Build()
	File_pkg_proto_inventory_inventory_proto = out.File
	file_pkg_proto_inventory_inventory_proto_goTypes = nil
	file_pkg_proto_inventory_inventory_proto_depIdxs = nil
}
